name: Checks ➜ Tests ➜ Publish

on:
  workflow_call:
    inputs:
      publish:
        description: "Флаг включения автоматической публикации модулей найденных в репозитории"
        default: true
        required: false
        type: boolean
      publish_branche:
        description: "Имя ветки, из который выполняется публикация модулей"
        default: "main"
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  eslint:
    name: ESLint Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: npm install
      - uses: nodutilus/project-actions/npm-build@test
      - run: npx nodutilus eslint
      - run: npx nodutilus eslintcc

  types:
    name: Types Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: npm install
      - uses: nodutilus/project-actions/npm-build@test
      - run: npx nodutilus ts-check

  tests:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: npm install
      - uses: nodutilus/project-actions/npm-build@test
      - run: npx nodutilus test

  coverage:
    name: Coverage Checking
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: npm install
      - uses: nodutilus/project-actions/npm-build@test
      - run: npx nodutilus c8

  build-and-publish:
    name: Build & Publish
    needs: [eslint, types, tests, coverage]
    if: github.event_name == 'push' && inputs.publish && github.ref_name == inputs.publish_branche
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: npm install
      - uses: nodutilus/project-actions/npm-build@test
      - uses: nodutilus/project-actions/npm-publish@test
        with:
          token: ${{ secrets.NPM_TOKEN }}
